NAME = btc

CC = c++

CPPFLAGS =  -Wall -Werror -Wextra -std=c++98

FILES = main.cpp BitcoinExchange.cpp

RM = rm -f

objects = $(FILES:.c=.o)

all : $(NAME)

$(NAME):$(objets)
		$(CC) $(CPPFLAGS) -o $(NAME) $(FILES)

clean :
		$(RM) $(NAME)

re : clean all

