NNAME = chanage

CC = c++

CPPFLAGS = -Wall -Werror -Wextra -std=c++98 #-fsanitize=address -g

FILES = main.cpp change.cpp

RM = rm -f

all : $(NNAME)

$(NNAME) : $(FILES)
			$(CC) $(CPPFLAGS) $(FILES) -o $(NNAME)

clean :
		$(RM) $(NNAME)

re : clean all
